<?php

namespace ReclamationBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function searrecchBy($searchPara){
        $qb = $this ->createQueryBuilder('c');

        $qb->Where('c.titre LIKE :sujet')
            ->setParameter('sujet','%'.$searchPara.'%');


        return $qb->getQuery()->getResult();
    }
    public function findReclamtion()
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT COUNT (r) FROM ReclamationBundle:reclamation r WHERE r.sujet LIKE 'Recycler %'");

        return $query->getResult();
    }

    public function findReclamationParent()
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT COUNT(r) FROM ReclamationBundle:reclamation  WHERE r.sujet='Achat'");
        return $query->getResult();
    }
    public function findReclamationClub()
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT COUNT(r) FROM ReclamationBundle:reclamation  WHERE r.sujet='Don'");
        return $query->getResult();
    }
    public function searreccourhBy($searchPara){
        $qb = $this ->createQueryBuilder('c');

        $qb->Where('c.titre LIKE :titre')
            ->setParameter('titre','%'.$searchPara.'%');


        return $qb->getQuery()->getResult();
    }
}