pai:
    resource: "@PaiBundle/Resources/config/routing.yml"
    prefix:   /pai

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /Reclamation

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog


app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"