<?php

namespace BlogBundle\Repository;

/**
 * desRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class desRepository extends \Doctrine\ORM\EntityRepository
{
}
